### ISSUE TITLE
OpenTelemetry-Operator not running

### ISSUE THREAD

**Issue by frzifus** [redhat-et/rosa-apps#41]
When I tried to check the logs to see why the collector I created was not created as a deployment, it appeared that the operator was not currently running.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: ingest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

cc @sallyom
